name: Skilled
main: cc.isotopestudio.Skilled.Skilled

author: Mars
description: Jobs
website: http://isotopestudio.cc
version: 1.0
commands:
  class:
    description: Skilled Command.
    usage: /<command>
#    aliases: rpg